import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bogle = localFont({
  src: "../public/fonts/BBHSansBogle-Regular.ttf",
  variable: "--font-bogle",
  weight: "400",
  style: "normal",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="silk" lang="en">
      <body
        className={`${bogle.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
